// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85zl-N2lhGDIioX3saexFRk04Jy320nw',
    appId: '1:43304839633:web:f1381cc7354196705ad8f0',
    messagingSenderId: '43304839633',
    projectId: 'loginmate-7a339',
    authDomain: 'loginmate-7a339.firebaseapp.com',
    storageBucket: 'loginmate-7a339.firebasestorage.app',
    measurementId: 'G-BMDVGRYQEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq20z3HFWMmdSWGuFbjdryQsJY_FixsWc',
    appId: '1:43304839633:android:5c396d0f4cbc6ee95ad8f0',
    messagingSenderId: '43304839633',
    projectId: 'loginmate-7a339',
    storageBucket: 'loginmate-7a339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVg8MXIyL4lk7cZAdGlWuHkX74fG-rMI',
    appId: '1:43304839633:ios:55a4c64eddba4ae25ad8f0',
    messagingSenderId: '43304839633',
    projectId: 'loginmate-7a339',
    storageBucket: 'loginmate-7a339.firebasestorage.app',
    iosBundleId: 'com.c.loginmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVg8MXIyL4lk7cZAdGlWuHkX74fG-rMI',
    appId: '1:43304839633:ios:403b94b5a4d7dd2d5ad8f0',
    messagingSenderId: '43304839633',
    projectId: 'loginmate-7a339',
    storageBucket: 'loginmate-7a339.firebasestorage.app',
    iosBundleId: 'com.example.loginmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85zl-N2lhGDIioX3saexFRk04Jy320nw',
    appId: '1:43304839633:web:00f6e092f50622575ad8f0',
    messagingSenderId: '43304839633',
    projectId: 'loginmate-7a339',
    authDomain: 'loginmate-7a339.firebaseapp.com',
    storageBucket: 'loginmate-7a339.firebasestorage.app',
    measurementId: 'G-X5VDHN371S',
  );
}
